access-company/antikythera_instance_example

- .tool-versions
- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/146116
> [146116] Fix Erlang and Elixir versions not depend on Antikythera

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/150737
> [150737] Upgrade elixir version to v1.7.4

- mix.exs
- mix.lock
ticket: https://acsmine.tok.access-company.com/redmine/issues/183314
> [183314] manually update antikythera commit hash

- .gitignore
https://acsmine.tok.access-company.com/redmine/issues/185700
> [185700] add `/_build_local` to .gitignore

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/185700
> [85700] update exsync and meck

- .tool-versions
ref: https://github.com/access-company/antikythera/pull/110
redmine: https://acsmine.tok.access-company.com/redmine/issues/201030
> [201030] Update Erlang OTP 20.3.8.25

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/201527
ref: https://github.com/access-company/antikythera/pull/114
> [201527] Upgrade Elixir to 1.9.4

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/209197
ref: https://github.com/access-company/antikythera/pull/139
> [209197] Update Erlang to 20.3.8.26

- .tool-versions
Reverts access-company/antikythera_instance_example#13
> Revert "[209197] Update Erlang to 20.3.8.26"

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/212875#note-32
> [212875] Update Erlang OTP 20.3.8.26

- README.md
- config/config.exs
- lib/antikythera_instance_example.ex
- mix.exs
- test/test_helper.exs
https://acsmine.tok.access-company.com/redmine/issues/221322
ドキュメントとコメント部分の copyright の変更のみのため、レビュースキップします。
> [221322] Update copyright year

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/235114#note-6
> [235114] Accept version with suffix in .tool-versions

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/157956#note-68
> [157956] Upgrade Erlang/OTP to 22.3.4.21

- README.md
- config/config.exs
- lib/antikythera_instance_example.ex
- mix.exs
- test/test_helper.exs
https://acsmine.tok.access-company.com/redmine/issues/241399
I'll skip the review since it's just comments and documentation updates.
> [241399] Update copyright year

- README.md
- config/config.exs
- lib/antikythera_instance_example.ex
- mix.exs
- test/test_helper.exs
https://acsmine.tok.access-company.com/redmine/issues/255994
Updated copyright year.
I'll skip the review since the PR includes only document updates.
> [255944] update copyright year

- .tool-versions
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/239881
This PR is required to pass CI checks of antikythera.
cf. access-company/antikythera#216
> [239881] Upgrade Elixir: 1.9.4 → 1.11.4

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/233827#note-16
> [233827] Preparation for release generation using Mix release

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/261457
> [261457] Update Antikythera for syn to skip compatibility test

- .tool-versions
- config/config.exs
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/239901
cf. access-company/antikythera#237
> [239901] Upgrade Elixir: 1.11.4 → 1.13.4

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/239901
This PR does not require any review because it just updates Antikythera commit hash.
> [239901] Update Antikythera

- .tool-versions
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/231052
> [231052] Upgrade OTP to 24

- .markdownlint-cli2.yaml
https://acsmine.tok.access-company.com/redmine/issues/271111
> [271111] Introduce markdownlint

- README.md
- config/config.exs
- lib/antikythera_instance_example.ex
- mix.exs
- test/test_helper.exs
https://acsmine.tok.access-company.com/redmine/issues/285220
I'll skip the review since the PR includes only document and comment updates.
> [285220] Update copyright year

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/289510
> [289510] Add yaml_elixir to be used by testgear tests

- .tool-versions
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/265200
> [265200] Upgrade Elixir to 1.15

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/265200
> [265200] Update Antikythera

- .tool-versions
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/310948
> [310948] Upgrade Erlang/OTP to 26.2.5.14
